"""Generate test/test_core/feed_sample.h: a real display feed (hvaccloud/display.py) for the
feed-parser test, from the same scenario as hvac-cloud/tests/test_display.py (a weak capacitor
raised as an alert, with its marker on the trend)."""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CLOUD = os.path.join(HERE, "..", "..", "..", "hvac-cloud")
sys.path.insert(0, CLOUD)

from sqlalchemy import create_engine, select  # noqa: E402
from sqlalchemy.pool import StaticPool  # noqa: E402

from hvaccloud import display  # noqa: E402
from hvaccloud.db import Account, System, init_db, session_factory  # noqa: E402
from hvaccloud.refrigerants import Tables  # noqa: E402
from tests.test_display import T0, WEAK_CAP, feed_world  # noqa: E402
from tests.test_electrical import reading  # noqa: E402

engine = create_engine("sqlite://", poolclass=StaticPool, connect_args={"check_same_thread": False})
init_db(engine)
sessions = session_factory(engine)
with sessions() as s, s.begin():
    a = Account(name="A", email="a@example.com")
    s.add(a)
    s.flush()
    s.add(System(account_id=a.id, name="Home", site_id="home"))
sid, _, cycle = feed_world(sessions, Tables(lambda *a: None))
for k in range(30):
    cycle(T0 + 10 * k, reading())
for k in range(30, 60):
    cycle(T0 + 10 * k, reading(**WEAK_CAP))
with sessions() as s:
    feed = display.build(s, s.get(System, sid), T0 + 600)
text = json.dumps(feed, separators=(",", ":"))
out = os.path.join(HERE, "..", "test", "test_core", "feed_sample.h")
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Generated by tools/make_feed_sample.py from hvaccloud/display.py. Do not edit.\n#pragma once\n")
    f.write("static const char FEED_SAMPLE[] = " + json.dumps(text) + ";\n")
    f.write(f"static const int FEED_SAMPLE_POINTS = {len(feed['tech']['trend']['on'])};\n")
print(f"{len(text)} bytes, {len(feed['alerts'])} alerts, {len(feed['tech']['markers'])} markers -> {os.path.relpath(out)}")
