"""Contractor demo: a separate demo account whose homes act out common faults.

  python demo.py setup     create the demo account, six homes and a day of history
  python demo.py run       keep the homes live (Ctrl+C to stop)
  python demo.py reset     delete everything the demo created (the rest of the database is untouched)

Sign in with the demo contractor account to show the fleet page, alerts, the technician view,
equipment and service history; the Garcia homeowner account shows the homeowner page. The
passwords are generated by `setup` and saved in demo-login.txt (git-ignored).

Readings go straight through the ingest code (no MQTT or nodes needed) into whichever database
DATABASE_URL points at. Demo systems never send alert email.
"""
import argparse
import datetime as dt
import json
import math
import os
import random
import secrets
import sys
import time

from sqlalchemy import delete, select

from hvaccloud import auth, settings
from hvaccloud.db import (Account, Alert, AlertMute, AlertPrefs, ApiKey, Command, Device, Equipment, Invite,
                          MaintenanceItem, PasswordReset, RuntimeDay, ServiceInfo, ServiceVisit, Snapshot, System,
                          SystemMember, Telemetry, User, UserSession, as_utc, init_db, make_engine, session_factory, utcnow)
from hvaccloud.ingest import Ingest
from hvaccloud.refrigerants import Tables

ACCOUNT = {"name": "Desert Air Demo Co.", "email": "demo@fullscope.example"}
CONTRACTOR = {"name": "Desert Air Demo Co.", "phone": "(480) 555-0100", "email": "service@fullscope.example"}
TECH_LOGIN = "demo@fullscope.example"
HOMEOWNER_LOGIN = "garcia@fullscope.example"
LOGIN_FILE = os.path.join(settings.HERE, "demo-login.txt")
STEP_S = 5                     # live reading interval, like the firmware
BACKFILL_H, BACKFILL_STEP_S = 24, 60

# Six homes. "on"/"off" are cycle minutes (None = running continuously, as on a hot Arizona day).
HOMES = [
    {"site": "demo-garcia", "name": "Garcia residence", "scenario": "healthy", "tons": 3.0, "on": 38, "off": 12,
     "filter_days": 21, "story": "Everything normal: what a healthy system looks like."},
    {"site": "demo-thompson", "name": "Thompson residence", "scenario": "dirty_filter", "tons": 3.5, "on": None, "off": None,
     "filter_days": 118, "story": "Low delta-T and an overdue filter: an easy homeowner fix."},
    {"site": "demo-patel", "name": "Patel home", "scenario": "low_charge", "tons": 4.0, "on": None, "off": None,
     "filter_days": 35, "story": "High superheat, low subcooling: a slow leak."},
    {"site": "demo-miller", "name": "Miller rental", "scenario": "blocked_condenser", "tons": 2.5, "on": None, "off": None,
     "filter_days": 50, "story": "Condensing 36+ F over ambient: dirty coil or blocked airflow outside."},
    {"site": "demo-nguyen", "name": "Nguyen casita", "scenario": "monitor_offline", "tons": 1.5, "on": 30, "off": 15,
     "filter_days": 60, "story": "The indoor monitor stopped reporting 3 hours ago."},
    {"site": "demo-brooks", "name": "Brooks home", "scenario": "floodback", "tons": 3.0, "on": None, "off": None,
     "filter_days": 12, "story": "Superheat near zero: liquid floodback risk, service needed."},
]
OFFLINE_SINCE_H = 3

# Pressures (psig) and line temps (F) per scenario; R-410A at ~14.0 psia (Mesa, AZ).
# dew 120 psig = 40.4 F, 98 = 30.1, 108 = 35.1, 128 = 43.9; bubble 420 = ~119.5, 330 = ~102.3, 520 = ~136.5
SCENARIOS = {
    "healthy":           {"p_vap": 120, "t_suc": 51.5, "p_liq": 420, "sc": 10.0, "dt": 19.5},
    "dirty_filter":      {"p_vap": 108, "t_suc": 44.0, "p_liq": 400, "sc": 10.0, "dt": 10.0},
    "low_charge":        {"p_vap": 98,  "t_suc": 63.0, "p_liq": 330, "sc": 2.0,  "dt": 15.0},
    "blocked_condenser": {"p_vap": 128, "t_suc": 56.0, "p_liq": 520, "sc": 11.0, "dt": 17.0, "oat_cap": 100},
    "monitor_offline":   {"p_vap": 120, "t_suc": 52.0, "p_liq": 410, "sc": 9.5,  "dt": 19.0},
    "floodback":         {"p_vap": 128, "t_suc": 45.5, "p_liq": 430, "sc": 13.0, "dt": 21.0},
}


def outdoor_temp(t):
    """Arizona summer day: ~84 F before dawn to ~108 F mid-afternoon (local time)."""
    hour = dt.datetime.fromtimestamp(t).hour + dt.datetime.fromtimestamp(t).minute / 60
    return 96 + 12 * math.sin((hour - 9.5) / 24 * 2 * math.pi)


def running(home, t, index):
    if home["on"] is None:
        return True
    period = (home["on"] + home["off"]) * 60
    return ((t + index * 437) % period) < home["on"] * 60


def readings(home, t, index, tables):
    """(outdoor JSON, indoor JSON or None) for a home at time t, as the firmware would send them."""
    sc = SCENARIOS[home["scenario"]]
    on = running(home, t, index)
    oat = outdoor_temp(t)
    if "oat_cap" in sc:
        oat = min(oat, sc["oat_cap"])
    j = lambda x: x + random.uniform(-0.3, 0.3)
    if on:
        p_vap, p_liq = j(sc["p_vap"]), j(sc["p_liq"] + 2 * (oat - 96))
        sat_high = tables.bubble_f("R-410A", p_liq + 14.0)
        t_suc, t_liq = j(sc["t_suc"]), j(sat_high - sc["sc"])
    else:                                     # pressures equalise, lines drift to ambient
        p_vap = p_liq = j(240 + oat)
        t_suc, t_liq = j(oat - 4), j(oat - 1)
    out = {"node": "outdoor", "fw": "demo", "rssi": -60, "uptime": int(t) % 864000,
           "mode": {"Y": on, "OB": on}, "p": {"liq": round(p_liq, 1), "vap": round(p_vap, 1), "tsuc": None},
           "t": {"suc": round(t_suc, 1), "liq": round(t_liq, 1), "tsuc": None, "dis": None},
           "air": {"t": round(j(oat), 1), "rh": 14.0}, "v5": 5.02, "err": []}
    if home["scenario"] == "monitor_offline" and t > time.time() - OFFLINE_SINCE_H * 3600:
        return out, None
    ret = j(77.0)
    supply = ret - sc["dt"] if on else ret - 1
    ind = {"node": "indoor", "fw": "demo", "rssi": -55, "uptime": int(t) % 864000,
           "mode": {"Y": on, "W": False, "G": on, "OB": on},
           "air": {"supply": round(j(supply), 1), "return": round(ret, 1), "dt": None}, "err": []}
    return out, ind


def feed(ingest, systems, t, tables):
    for index, home in enumerate(HOMES):
        out, ind = readings(home, t, index, tables)
        if ind is not None:
            ingest.handle(f"hvac/{home['site']}/indoor/telemetry", json.dumps(ind).encode(), now=t)
        ingest.handle(f"hvac/{home['site']}/outdoor/telemetry", json.dumps(out).encode(), now=t + 1)


def demo_account(s):
    return s.scalar(select(Account).where(Account.email == ACCOUNT["email"], Account.name == ACCOUNT["name"]))


def setup(sessions):
    tables = Tables(lambda *a: None)
    today = dt.date.today()
    tech_pw, owner_pw = secrets.token_urlsafe(9), secrets.token_urlsafe(9)
    with sessions() as s, s.begin():
        if demo_account(s) is not None:
            sys.exit("The demo already exists. Run `python demo.py reset` first to start over.")
        if s.scalar(select(User).where(User.email.in_([TECH_LOGIN, HOMEOWNER_LOGIN]))):
            sys.exit(f"{TECH_LOGIN} or {HOMEOWNER_LOGIN} already has a sign-in; remove it first.")
        acct = Account(**ACCOUNT)
        s.add(acct)
        s.flush()
        s.add(User(email=TECH_LOGIN, name="Demo technician", role="contractor", account_id=acct.id,
                   password_hash=auth.hash_password(tech_pw)))
        for i, home in enumerate(HOMES):
            if s.scalar(select(System).where(System.site_id == home["site"])):
                sys.exit(f"site {home['site']} is already used")
            sy = System(account_id=acct.id, name=home["name"], site_id=home["site"], refrigerant="R-410A",
                        heat_pump=True, ob_energized="cool", atm_psia=14.0)
            s.add(sy)
            s.flush()
            s.add(Equipment(system_id=sy.id, system_type="split_hp", metering="txv", tonnage=home["tons"],
                            sc_target=10.0, sc_tolerance=4.0, elevation_ft=1240))
            s.add(ServiceInfo(system_id=sy.id, **CONTRACTOR))
            s.add(AlertPrefs(system_id=sy.id, email_owner=False, email_contractor=False))   # demo never emails
            s.add(MaintenanceItem(system_id=sy.id, kind="filter", interval_days=90, interval_run_hours=500.0,
                                  last_done=today - dt.timedelta(days=home["filter_days"])))
            s.add(MaintenanceItem(system_id=sy.id, kind="tuneup", interval_days=182,
                                  last_done=today - dt.timedelta(days=40 + 25 * i)))
            hours = 10.0 if home["scenario"] == "dirty_filter" else 6.0   # only Thompson's filter is overdue
            for d in range(min(home["filter_days"], 120)):
                s.add(RuntimeDay(system_id=sy.id, day=today - dt.timedelta(days=d), blower_s=hours * 3600,
                                 compressor_s=(hours - 1) * 3600))
            s.add(ServiceVisit(system_id=sy.id, date=today - dt.timedelta(days=40 + 25 * i), kind="tuneup",
                               technician="Demo technician", work="Spring tune-up: cleaned condenser coil, checked charge "
                               "and capacitor, tightened electrical connections.", filter_changed=False))
            if home["scenario"] == "low_charge":
                s.add(ServiceVisit(system_id=sy.id, date=today - dt.timedelta(days=400), kind="repair",
                                   technician="Demo technician", work="Added 1.5 lb R-410A; recommended a leak search."))
            if home["scenario"] == "healthy":
                owner = User(email=HOMEOWNER_LOGIN, name="Maria Garcia", role="homeowner",
                             password_hash=auth.hash_password(owner_pw))
                s.add(owner)
                s.flush()
                s.add(SystemMember(system_id=sy.id, user_id=owner.id))
        acct_id = acct.id
    with open(LOGIN_FILE, "w", encoding="utf-8") as f:
        f.write(f"Fullscope demo sign-ins (made by demo.py setup; local only, not committed)\n\n"
                f"Contractor:  {TECH_LOGIN}  /  {tech_pw}\nHomeowner:   {HOMEOWNER_LOGIN}  /  {owner_pw}\n")

    print(f"Demo account {acct_id} created with {len(HOMES)} homes. Backfilling {BACKFILL_H} h of readings...")
    # readings a minute apart: tell the ingest so it doesn't take each gap for an outage
    ingest = Ingest(sessions, tables, stale=2 * BACKFILL_STEP_S)
    t0 = time.time() - BACKFILL_H * 3600
    steps = BACKFILL_H * 3600 // BACKFILL_STEP_S
    for k in range(steps):
        feed(ingest, None, t0 + k * BACKFILL_STEP_S, tables)
        if k % 240 == 0:
            print(f"  {100 * k // steps} %", flush=True)
    past_alerts(sessions, acct_id)
    print(f"Done. Sign-ins saved in {LOGIN_FILE}. Keep it live with `python demo.py run`.")


def past_alerts(sessions, acct_id):
    """A little history for the alert logs: problems that came and went earlier in the week."""
    now = utcnow()
    ago = lambda days, hours=0: now - dt.timedelta(days=days, hours=hours)
    history = {"demo-garcia": [("dt_low", "warn", "Air delta-T 11.2°F is low", ago(4, 3), 45)],
               "demo-miller": [("no_data", "warn", "No readings from either node for 10 min", ago(2, 5), 70)],
               "demo-brooks": [("sh_low", "alert", "Superheat 2.4°F: risk of liquid floodback", ago(6, 2), 30)]}
    with sessions() as s, s.begin():
        for sy in s.scalars(select(System).where(System.account_id == acct_id)):
            for code, level, text, start, minutes in history.get(sy.site_id, []):
                end = start + dt.timedelta(minutes=minutes)
                s.add(Alert(system_id=sy.id, code=code, level=level, text=text, started_at=start, last_seen=end,
                            raised_at=start + dt.timedelta(minutes=5), cleared_at=end + dt.timedelta(minutes=5)))


def catch_up(sessions, ingest, tables):
    """Fill the gap since the demo last ran (up to a day), so the homes look like they kept running
    instead of coming back from an outage (which restarts run timers and closes alerts)."""
    with sessions() as s:
        acct = demo_account(s)
        ids = list(s.scalars(select(System.id).where(System.account_id == acct.id)))
        last = s.scalar(select(Snapshot.time).where(Snapshot.system_id.in_(ids)).order_by(Snapshot.time.desc()).limit(1))
    now = time.time()
    start = max(now - BACKFILL_H * 3600, as_utc(last).timestamp() if last else now - BACKFILL_H * 3600)
    if now - start < 2 * STEP_S:
        return
    print(f"Catching up {round((now - start) / 60)} min since the demo last ran...")
    ingest.stale = 2 * BACKFILL_STEP_S
    t = start + BACKFILL_STEP_S
    while t < now:
        feed(ingest, None, t, tables)
        t += BACKFILL_STEP_S
    feed(ingest, None, time.time() - 2, tables)
    ingest.stale = settings.STALE_SECONDS


def run(sessions):
    tables = Tables(lambda *a: None)
    with sessions() as s:
        if demo_account(s) is None:
            sys.exit("No demo yet: run `python demo.py setup` first.")
    ingest = Ingest(sessions, tables)
    catch_up(sessions, ingest, tables)
    print(f"Demo running: {len(HOMES)} homes, a reading every {STEP_S} s (Ctrl+C to stop).")
    last_sweep = 0.0
    try:
        while True:
            now = time.time()
            feed(ingest, None, now, tables)
            if now - last_sweep >= 60:
                ingest.sweep(now)
                last_sweep = now
            time.sleep(max(0.5, STEP_S - (time.time() - now)))
    except KeyboardInterrupt:
        print("stopped")


def reset(sessions):
    """Delete the demo account and everything that belongs to it, and nothing else."""
    with sessions() as s, s.begin():
        acct = demo_account(s)
        if acct is None:
            print("No demo account found; nothing to delete.")
            return
        sys_ids = list(s.scalars(select(System.id).where(System.account_id == acct.id)))
        dev_ids = list(s.scalars(select(Device.id).where(Device.system_id.in_(sys_ids))))
        user_ids = list(s.scalars(select(User.id).where(User.account_id == acct.id)))
        user_ids += list(s.scalars(select(SystemMember.user_id).where(SystemMember.system_id.in_(sys_ids))))
        for model, col, ids in [(Telemetry, Telemetry.device_id, dev_ids), (Command, Command.device_id, dev_ids)]:
            s.execute(delete(model).where(col.in_(ids)))
        for model in (Snapshot, Alert, AlertMute, AlertPrefs, Equipment, ServiceInfo, MaintenanceItem, RuntimeDay,
                      ServiceVisit, SystemMember, Device):
            s.execute(delete(model).where(model.system_id.in_(sys_ids)))
        s.execute(delete(Invite).where((Invite.system_id.in_(sys_ids)) | (Invite.account_id == acct.id)))
        s.execute(delete(UserSession).where(UserSession.user_id.in_(user_ids)))
        s.execute(delete(PasswordReset).where(PasswordReset.user_id.in_(user_ids)))
        s.execute(delete(User).where(User.id.in_(user_ids), User.email.like("%@fullscope.example")))
        s.execute(delete(ApiKey).where(ApiKey.account_id == acct.id))
        s.execute(delete(System).where(System.id.in_(sys_ids)))
        s.delete(acct)
    if os.path.exists(LOGIN_FILE):
        os.remove(LOGIN_FILE)
    print(f"Demo removed ({len(sys_ids)} homes).")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("command", choices=["setup", "run", "reset"])
    args = ap.parse_args(argv)
    engine = make_engine()
    init_db(engine)
    sessions = session_factory(engine)
    {"setup": setup, "run": run, "reset": reset}[args.command](sessions)


if __name__ == "__main__":
    main()
