"""Generate radio/lora/test/test_lorafmt/vectors.h from lorafmt.py (the reference): random
readings, commands, replies, statuses and a gateway session, with the exact bytes and JSON the
C++ port must produce (pio test -e native in radio/lora). Run with the radio venv:

    radio\\.venv\\Scripts\\python.exe radio\\tools\\make_cpp_vectors.py
"""
import json
import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, ".."))
import lorafmt as lf  # noqa: E402

KEY = bytes(range(16))
KEY2 = bytes(range(16, 32))
RECEIVED_AT = 1_791_000_000.25
rng = random.Random(7)


def maybe(v, p=0.12):
    return None if rng.random() < p else v


def num(lo, hi, places=3):
    """A random value that is never an exact rounding tie when packed (x10 or x100): JSON parsers can
    read a decimal 1 ulp apart, which only matters exactly on a tie."""
    while True:
        v = round(rng.uniform(lo, hi), places)
        if all(abs((v * s) % 1 - 0.5) > 1e-6 and abs(((v - 4) * s) % 1 - 0.5) > 1e-6 for s in (10, 100)):
            return v


def outdoor_doc():
    errs = rng.sample(lf.OUTDOOR_ERRS + ["weird_one"], rng.choice([0, 0, 0, 1, 2]))
    return {"node": "outdoor", "fw": "0.2.0", "rssi": -60, "uptime": rng.randrange(0, 2_000_000),
            "mode": {"Y": rng.random() < 0.6, "OB": rng.random() < 0.5},
            "p": {"liq": maybe(num(80, 620)), "vap": maybe(num(40, 180)), "tsuc": maybe(num(40, 180), 0.6)},
            "t": {"suc": maybe(num(20, 90)), "liq": maybe(num(60, 130)), "tsuc": maybe(num(20, 90), 0.6),
                  "dis": maybe(num(100, 250), 0.6)},
            "air": {"t": maybe(num(-10, 120)), "rh": maybe(num(0, 100))}, "v5": maybe(num(4.5, 5.5, 4)), "err": errs}


def indoor_doc():
    errs = rng.sample(lf.INDOOR_ERRS + ["odd"], rng.choice([0, 0, 0, 1]))
    return {"node": "indoor", "fw": "0.2.0", "uptime": rng.randrange(0, 2_000_000),
            "mode": {k: rng.random() < 0.5 for k in ("Y", "W", "G", "OB")},
            "air": {"supply": maybe(num(40, 130)), "return": maybe(num(55, 90)), "dt": None}, "err": errs}


def c_str(s):
    return json.dumps(s)


def hexs(b):
    return b.hex()


def main():
    out = ["// Generated by radio/tools/make_cpp_vectors.py from radio/lorafmt.py. Do not edit.", "#pragma once", "",
           "static const char* const V_KEY = \"" + KEY.hex() + "\";", "static const char* const V_KEY2 = \"" + KEY2.hex() + "\";",
           f"static const double V_RECEIVED_AT = {RECEIVED_AT!r};", ""]
    # ---- readings
    out.append("struct VReading { const char* doc; unsigned age; unsigned dev, counter; const char* payload; const char* frame; const char* json; };")
    out.append("static const VReading V_READINGS[] = {")
    for i in range(300):
        doc = outdoor_doc() if i % 2 == 0 else indoor_doc()
        age = rng.choice([0, 0, 0, 5, 300, 70000])
        dev, counter = rng.randrange(1, 2**32), rng.randrange(0, 2**32)
        ftype, payload = lf.pack_reading(doc, age)
        frame = lf.seal(KEY, dev, counter, ftype, payload)
        back = lf.unpack_reading(ftype, payload, RECEIVED_AT)
        out.append(f"    {{{c_str(json.dumps(doc))}, {age}, {dev}u, {counter}u, \"{hexs(payload)}\", \"{hexs(frame)}\", {c_str(json.dumps(back))}}},")
    out += ["};", ""]
    # ---- status
    out.append("struct VStatus { const char* fw; unsigned interval_ms, backlog, dropped; const char* payload; const char* json; };")
    out.append("static const VStatus V_STATUS[] = {")
    for fw, iv, bl, dr in [("0.2.0", 5000, 0, 0), ("1.12.3", 300000, 40, 7), ("0.3.1", 100_000_000, 999, 70000)]:
        _, payload = lf.pack_status(fw, iv, bl, dr)
        out.append(f"    {{\"{fw}\", {iv}u, {bl}u, {dr}u, \"{hexs(payload)}\", {c_str(json.dumps(lf.unpack_status(payload)))}}},")
    out += ["};", ""]
    # ---- commands
    cmds = [{"cmd": "status"}, {"cmd": "reboot"}, {"cmd": "interval", "ms": 5000}, {"cmd": "interval", "ms": 12345},
            {"cmd": "cal_zero", "ch": "p_liq"}, {"cmd": "cal_span", "ch": "p_vap", "ref": 300.5},
            {"cmd": "cal_ref", "ch": "t_suc", "ref": 54.3}, {"cmd": "cal_set", "ch": "t_liq", "offset": -0.7},
            {"cmd": "cal_reset", "ch": "p_tsuc"}, {"cmd": "range", "ch": "p_liq", "bar": 50},
            {"cmd": "fitted", "ch": "t_tsuc", "on": True}, {"cmd": "fitted", "ch": "t_dis", "on": False},
            {"cmd": "ntc_b", "value": 3950}, {"cmd": "v33", "value": 3.312}, {"cmd": "ds_swap"}, {"cmd": "rescan"},
            {"cmd": "cal_zero", "ch": "t_sup"}, {"cmd": "cal_ref", "ch": "t_ret", "ref": 72.25}]
    bad = [{"cmd": "selfdestruct"}, {"cmd": "cal_zero", "ch": "p_nope"}, {"cmd": "cal_set", "ch": "p_liq", "offset": 1, "scale": 1.01}]
    out.append("struct VCommand { const char* cmd; const char* payload; const char* json; };   // payload \"\" = refused")
    out.append("static const VCommand V_COMMANDS[] = {")
    for c in cmds:
        _, payload = lf.pack_command(c)
        out.append(f"    {{{c_str(json.dumps(c))}, \"{hexs(payload)}\", {c_str(json.dumps(lf.unpack_command(payload)))}}},")
    for c in bad:
        out.append(f"    {{{c_str(json.dumps(c))}, \"\", \"\"}},")
    out += ["};", ""]
    # ---- replies
    replies = [{"cmd": "cal_zero", "ok": True, "ch": "p_liq", "offset": -1.25, "scale": 1.0},
               {"cmd": "cal_span", "ok": True, "ch": "p_vap", "offset": 0.4, "scale": 1.0123},
               {"cmd": "cal_span", "ok": False, "error": "apply at least ~50 psi before spanning"},
               {"cmd": "interval", "ok": True, "ms": 10000}, {"cmd": "ntc_b", "ok": True, "ntc_b": 3950},
               {"cmd": "status", "ok": True}, {"cmd": "zap", "ok": False, "error": "unknown command"},
               {"cmd": "cal_set", "ok": False, "error": "something new"}, {"cmd": "range", "ok": True, "fs_bar": 35}]
    out.append("struct VReply { const char* reply; const char* payload; const char* json; };")
    out.append("static const VReply V_REPLIES[] = {")
    for r in replies:
        _, payload = lf.pack_reply(r)
        out.append(f"    {{{c_str(json.dumps(r))}, \"{hexs(payload)}\", {c_str(json.dumps(lf.unpack_reply(payload)))}}},")
    out += ["};", ""]
    # ---- a gateway session: what lorafmt.Gateway does with each frame
    devices = {0x0A0B0C0D: {"key": KEY, "site": "home", "node": "outdoor"}, 0x01020304: {"key": KEY2, "site": "home", "node": "indoor"}}
    gw = lf.Gateway(devices)
    session = []
    o, i = outdoor_doc(), indoor_doc()
    f1 = lf.seal(KEY, 0x0A0B0C0D, 10, *lf.pack_reading(o))
    session.append(f1)
    session.append(lf.seal(KEY2, 0x01020304, 3, *lf.pack_reading(i)))
    session.append(f1)                                                       # replayed
    session.append(lf.seal(KEY, 0x0A0B0C0D, 9, *lf.pack_reading(o)))        # counter went back
    session.append(lf.seal(KEY, 0x0A0B0C0D, 11, *lf.pack_status("0.3.0", 5000, 2, 1)))
    session.append(lf.seal(KEY, 0x0A0B0C0D, 12, *lf.pack_reply({"cmd": "cal_zero", "ok": True, "offset": 0.5, "scale": 1.0})))
    session.append(lf.seal(KEY2, 0x0A0B0C0D, 13, *lf.pack_reading(o)))      # wrong key
    session.append(lf.seal(KEY, 0x77777777, 1, *lf.pack_reading(o)))       # unknown device
    tampered = bytearray(lf.seal(KEY, 0x0A0B0C0D, 14, *lf.pack_reading(o)))
    tampered[12] ^= 1
    session.append(bytes(tampered))
    session.append(lf.seal(KEY, 0x0A0B0C0D, 15, *lf.pack_command({"cmd": "status"})))   # nodes don't send commands
    session.append(lf.seal(KEY, 0x0A0B0C0D, 16, *lf.pack_reading(o)))
    out.append("struct VGateway { const char* frame; const char* topic; const char* json; };   // topic \"\" = refused")
    out.append("static const VGateway V_GATEWAY[] = {")
    for k, frame in enumerate(session):
        try:
            topic, doc = gw.receive(frame, RECEIVED_AT + k, rssi=-97, snr=7.5)
            out.append(f"    {{\"{hexs(frame)}\", \"{topic}\", {c_str(json.dumps(doc))}}},")
        except ValueError:
            out.append(f"    {{\"{hexs(frame)}\", \"\", \"\"}},")
    out += ["};", ""]
    path = os.path.join(HERE, "..", "lora", "test", "test_lorafmt", "vectors.h")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"wrote {os.path.relpath(path)}")


if __name__ == "__main__":
    main()
